### ISSUE TITLE
[BUG] OpenVINO support in DNN module broken?

### ISSUE THREAD

**Issue by CSBVision** [emgucv/emgucv#879]
**Describe the bug**
After upgrading to 4.8.0, OpenVINO support in the DNN module seems to be broken. Even though OpenVINO itself is found - we even tested both, static and shared library builds of OpenVINO - which can be verified by the CMake output:
```
OpenVINO:                    YES (2023.0.1)
```
However, OpenCV's DNN module does not link against OpenVINO and, therefore, does not use it at all. Still, directly using OpenCV 4.8.0 with the same OpenVINO builds works fine. This pointed us towards commit https://github.com/emgucv/opencv/commit/560a0c15a18ef476ac9e88bd87986a02e4bde329 in which the line
```
list(APPEND dnn_runtime_libs ocv.3rdparty.openvino)
```
was removed from the default configuration and only will be executed if `OpenVINO_DIR` is not set, i.e. does not work in combination with prebuild OpenVINO. Here, from the status message in the following lines, we suspect this is a copy-paste error from the GAPI module. There, an `ocv_install_used_external_targets()` call was moved into an equivalent `if` block. Still, in the DNN module the call is not an `ocv_install_used_external_targets()` - as stated by the following line
```
MESSAGE(STATUS "Using prebuild OpenVINO, we will skip ocv_install_used_external_targets(ocv.3rdparty.openvino) in dnn module")
```
but instead appends OpenVINO to the list of runtime libraries. Undoing the above commit for the DNN module, i.e. always executing `list(APPEND dnn_runtime_libs ocv.3rdparty.openvino)` resolves this issue. Therefore, we suggest to undo this change or at least fix the commit.

** OS / Platform **
Windows

** .Net version **
.NetFramework 4.8

**CPU Architecture**
x86_64

** Emgu CV package used**
GitHub version 4.8.0

**To Reproduce**
Clone repository, checkout 4.8.0 release and try to link against a prebuild OpenVINO installation.

**Expected behavior**
OpenVINO used by the DNN module.

**Additional context**
Undoing commit https://github.com/emgucv/opencv/commit/560a0c15a18ef476ac9e88bd87986a02e4bde329 for the DNN module resolves the issue.

**Comment by emgucv** [comment]
Fixed in this commit:
058d52c4a10451507bb34e29dfe1dc4012582f3f
and this commit:
b21f1a48337a10ffb5a7086d732582d209c16606

The fix has been included in the 4.8.1 release.

**Comment by CSBVision** [comment]
Thanks for fixing 👍

**Comment by CSBVision** [comment]
Sorry for reopening this issue, but after updating to the recently available 4.9.0 version of OpenCV and recompiling, this issue still exists.

First, not adding OpenVINO to the dependencies of the DNN module - as caused by commit https://github.com/emgucv/opencv/commit/560a0c15a18ef476ac9e88bd87986a02e4bde329 - still breaks OpenVINO support in the DNN module if the latter is compiled as a shared library. For static builds of OpenCV, this might be fixed by the recent patches. Still, only adding `ocv.3rdparty.openvino` to the list of dependent libraries if OpenVINO was **not** found (i.e. `OpenVINO_DIR` is empty) seems incorrect - in which setting should this be useful at all?
Anyway, to support also shared library builds, the change in the DNN module's `CMakeLists.txt` could be extended to `IF (BUILD_SHARED_LIBS)` or - if the `OpenVINO_DIR` check should still be there - to `IF (BUILD_SHARED_LIBS OR "${OpenVINO_DIR}" STREQUAL "")` and this issue should by resolved in both cases. What do you think about this proposal?

Besides, a new issue appears after the recent updates. Now, there is a build event that tries to copy the file `<build_directory>/bin/Release/opencv_dnn_openvino490_64.dll` to `<source_directory>/libs/runtimes/win-x64/native`. This file does not exist for default OpenVINO builds. First, because OpenVINO does not depend on neither OpenCV nor its version and second, OpenVINO itself could be used as static libraries only such that there are no OpenVINO DLLs at all.  We propose to only copy this file if it exists. Otherwise, the copy command results in an error that terminates the compilation.

**Comment by emgucv** [comment]
Closing this thread with a summary of where things settled: the original linkage regression (from the `560a0c15` fork commit) was fixed in the 4.8.1 release, as confirmed above. For the follow-up concerning 4.9.0: since the 4.8 series, OpenVINO integrates with the DNN module through the **plugin architecture** — the build produces a separate `opencv_dnn_openvino*.dll` (analogous to the ffmpeg videoio plugin) which the DNN module loads at run time, rather than linking OpenVINO into the dnn library directly; that is the supported configuration, it is what the release build server uses (via `Build_Binary_x86-64_inf_doc.bat`), and your analysis of the two integration modes matches this design. The same plugin model carries forward unchanged into the upcoming 5.0 release (verified in the current tree: OpenCV 5's dnn retains the `dnn_plugin_openvino` build and the Emgu configuration retains the `WITH_OPENVINO` wiring). Directly linking a prebuilt OpenVINO into a shared-library dnn build remains outside the supported configuration. If the plugin path fails on a current release, please open a fresh issue with the CMake configuration output. Thanks for the unusually thorough analysis in this thread — it's what got the 4.8.1 fix made.
